#!/usr/bin/env bash
export MAVEN_OPTS="-Xmx2048m -Xms1024m -Djava.awt.headless=true"
cd modules/accounting
mvn datanucleus:enhance
cd ../activity
mvn datanucleus:enhance
cd ../assets
mvn datanucleus:enhance
cd ../auth
mvn datanucleus:enhance
cd ../config
mvn datanucleus:enhance
cd ../conversations
mvn datanucleus:enhance
cd ../dashboards
mvn datanucleus:enhance
cd ../domains
mvn datanucleus:enhance
cd ../entities
mvn datanucleus:enhance
cd ../event-handlers
mvn datanucleus:enhance
cd ../inventory
mvn datanucleus:enhance
cd ../logi
mvn datanucleus:enhance
cd ../materials
mvn datanucleus:enhance
cd ../media
mvn datanucleus:enhance
cd ../mnltransactions
mvn datanucleus:enhance
cd ../optimization
mvn datanucleus:enhance
cd ../orders
mvn datanucleus:enhance
cd ../predictions
mvn datanucleus:enhance
cd ../reports
mvn datanucleus:enhance
cd ../tags
mvn datanucleus:enhance
cd ../users
mvn datanucleus:enhance
