CREATE TABLE `APPROVERS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UID` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `KID` bigint(20) DEFAULT NULL,
  `CBY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `CON` datetime DEFAULT NULL,
  `UBY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `UON` datetime DEFAULT NULL,
  `TYPE` int(1) DEFAULT NULL,
  `OTYPE` varchar(255) DEFAULT NULL,
  `SDID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8;

CREATE TABLE `ORDER_APPROVAL_MAPPING` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint(20) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `APPROVAL_TYPE` int(1) DEFAULT NULL,
  `APPROVAL_ID` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  `UPDATED_AT` datetime DEFAULT NULL,
  `KIOSK_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

ALTER TABLE `ORDER` ADD COLUMN `VTC` tinyint(1) NOT NULL DEFAULT '1';
ALTER TABLE `ORDER` ADD COLUMN `VTV` tinyint(1) NOT NULL DEFAULT '1';
