-- useraccount having CITYID <Start>
ALTER TABLE `logistimo`.`USERACCOUNT`
ADD COLUMN `CITY_ID` CHAR(36) NULL DEFAULT NULL AFTER `LGSRC`;
-- useraccount having CITYID <End>

-- useraccount having COUNTRYID <Start>
ALTER TABLE `logistimo`.`USERACCOUNT`
ADD COLUMN `COUNTRY_ID` CHAR(36) NULL DEFAULT NULL AFTER `CITY_ID`;
-- useraccount having COUNTRYID <End>

-- useraccount having DISTID <Start>
ALTER TABLE `logistimo`.`USERACCOUNT`
ADD COLUMN `DISTRICT_ID` CHAR(36) NULL DEFAULT NULL AFTER `COUNTRY_ID`;
-- useraccount having DISTID <End>

-- useraccount having STATEID <Start>
ALTER TABLE `logistimo`.`USERACCOUNT`
ADD COLUMN `STATE_ID` CHAR(36) NULL DEFAULT NULL AFTER `DISTRICT_ID`;
-- useraccount having STATEID <End>

-- useraccount having SUBDISTID <Start>
ALTER TABLE `logistimo`.`USERACCOUNT`
ADD COLUMN `SUBDISTRICT_ID` CHAR(36) NULL DEFAULT NULL AFTER `STATE_ID`;
-- useraccount having SUBDISTID <End>

-- kiosk having CITYID <Start>
ALTER TABLE `logistimo`.`KIOSK`
ADD COLUMN `CITY_ID` CHAR(36) NULL DEFAULT NULL AFTER `AT`;
-- kiosk having CITYID <End>

-- kiosk having COUNTRYID <Start>
ALTER TABLE `logistimo`.`KIOSK`
ADD COLUMN `COUNTRY_ID` CHAR(36) NULL DEFAULT NULL AFTER `CITY_ID`;
-- kiosk having COUNTRYID <End>

-- kiosk having DISTID <Start>
ALTER TABLE `logistimo`.`KIOSK`
ADD COLUMN `DISTRICT_ID` CHAR(36) NULL DEFAULT NULL AFTER `COUNTRY_ID`;
-- kiosk having DISTID <End>

-- kiosk having STATEID <Start>
ALTER TABLE `logistimo`.`KIOSK`
ADD COLUMN `STATE_ID` CHAR(36) NULL DEFAULT NULL AFTER `DISTRICT_ID`;
-- kiosk having STATEID <End>

-- kiosk having SUBDISTID <Start>
ALTER TABLE `logistimo`.`KIOSK`
ADD COLUMN `SUBDISTRICT_ID` CHAR(36) NULL DEFAULT NULL AFTER `STATE_ID`;
-- kiosk having SUBDISTID <End>


CREATE TABLE `logistimo`.`LOCATIONFAILEDJOB` (
  `ID` BIGINT(20) NOT NULL,
  `TYPE` CHAR(36) NULL DEFAULT NULL,
  `PAYLOAD` VARCHAR(255) NULL DEFAULT NULL,
  `CREATEDATE` DATETIME NULL DEFAULT NULL,
  `PROCESSFLAG` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`));

  CREATE TABLE `logistimo`.`USERDEVICE` (
  `USERID` VARCHAR(255) NOT NULL,
  `TOKEN` VARCHAR(255) NOT NULL,
  `APPNAME` VARCHAR(255) NULL,
  `CREATEDON` DATETIME NULL,
  `UPDATEDON` DATETIME NULL,
  PRIMARY KEY (`USERID`));

ALTER TABLE TRANSACTION ADD ET DATETIME(3);


CREATE TABLE `APPROVERS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UID` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `KID` bigint(20) DEFAULT NULL,
  `CBY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `CON` datetime DEFAULT NULL,
  `UBY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `UON` datetime DEFAULT NULL,
  `TYPE` int(1) DEFAULT NULL,
  `OTYPE` varchar(255) DEFAULT NULL,
  `SDID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8;

CREATE TABLE `ORDER_APPROVAL_MAPPING` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint(20) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `APPROVAL_TYPE` int(1) DEFAULT NULL,
  `APPROVAL_ID` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  `UPDATED_AT` datetime DEFAULT NULL,
  `KIOSK_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

ALTER TABLE `USERACCOUNT` ADD COLUMN `THEME` TINYINT(1) DEFAULT -1;


ALTER TABLE `ORDER` ADD COLUMN `VTC` tinyint(1) NOT NULL DEFAULT '1',
ADD COLUMN `VTV` tinyint(1) NOT NULL DEFAULT '1',ADD COLUMN `SRC` int(3);


ALTER TABLE SHIPMENT ADD SRC int(3);
