
ALTER TABLE `logistimo`.`USERACCOUNT`
ADD COLUMN `CITY_ID` CHAR(36) NULL DEFAULT NULL AFTER `LGSRC`,
ADD COLUMN `COUNTRY_ID` CHAR(36) NULL DEFAULT NULL AFTER `CITY_ID`,
ADD COLUMN `DISTRICT_ID` CHAR(36) NULL DEFAULT NULL AFTER `COUNTRY_ID`,
ADD COLUMN `STATE_ID` CHAR(36) NULL DEFAULT NULL AFTER `DISTRICT_ID`,
ADD COLUMN `SUBDISTRICT_ID` CHAR(36) NULL DEFAULT NULL AFTER `STATE_ID`,
ADD COLUMN `THEME` TINYINT(1) DEFAULT -1;

ALTER TABLE `logistimo`.`KIOSK`
ADD COLUMN `CITY_ID` CHAR(36) NULL DEFAULT NULL AFTER `AT`,
ADD COLUMN `COUNTRY_ID` CHAR(36) NULL DEFAULT NULL AFTER `CITY_ID`,
ADD COLUMN `DISTRICT_ID` CHAR(36) NULL DEFAULT NULL AFTER `COUNTRY_ID`,
ADD COLUMN `STATE_ID` CHAR(36) NULL DEFAULT NULL AFTER `DISTRICT_ID`,
ADD COLUMN `SUBDISTRICT_ID` CHAR(36) NULL DEFAULT NULL AFTER `STATE_ID`;

CREATE TABLE `logistimo`.`LOCATIONFAILEDJOB` (
  `ID` BIGINT(20) NOT NULL,
  `TYPE` CHAR(36) NULL DEFAULT NULL,
  `PAYLOAD` VARCHAR(255) NULL DEFAULT NULL,
  `CREATEDATE` DATETIME NULL DEFAULT NULL,
  `PROCESSFLAG` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `logistimo`.`USERDEVICE` (
  `USERID` VARCHAR(255) NOT NULL,
  `TOKEN` VARCHAR(255) NOT NULL,
  `APPNAME` VARCHAR(255) NULL,
  `CREATEDON` DATETIME NULL,
  `UPDATEDON` DATETIME NULL,
  PRIMARY KEY (`USERID`));

ALTER TABLE `logistimo`.`TRANSACTION` ADD ET DATETIME(3) NULL AFTER `T`;


CREATE TABLE `logistimo`.`APPROVERS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UID` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `KID` bigint(20) DEFAULT NULL,
  `CBY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `CON` datetime DEFAULT NULL,
  `UBY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `TYPE` int(1) DEFAULT NULL,
  `OTYPE` varchar(255) DEFAULT NULL,
  `SDID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1345314 DEFAULT CHARSET=utf8;

CREATE TABLE `logistimo`.`ORDER_APPROVAL_MAPPING` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint(20) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `APPROVAL_TYPE` int(1) DEFAULT NULL,
  `APPROVAL_ID` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  `UPDATED_AT` datetime DEFAULT NULL,
  `KIOSK_ID` bigint(20) DEFAULT NULL,
  `LATEST` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ORDER_APPROVAL_MAPPING_UNIQUE` UNIQUE (`APPROVAL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1133465 DEFAULT CHARSET=utf8;


ALTER TABLE `logistimo`.`ORDER`
ADD COLUMN `VTC` tinyint(1) NOT NULL DEFAULT '1',
ADD COLUMN `VTV` tinyint(1) NOT NULL DEFAULT '1',
ADD COLUMN `SRC` int(3);

ALTER TABLE `logistimo`.`SHIPMENT` ADD SRC int(3);

ALTER TABLE `logistimo`.`MESSAGELOG` MODIFY COLUMN MSG varchar(2048);
