/usr/bin/native2ascii -encoding UTF-8 ./Messages_en.properties.orig ../Messages_en.properties
/usr/bin/native2ascii -encoding UTF-8 ./Messages_fr.properties.orig ../Messages_fr.properties
/usr/bin/native2ascii -encoding UTF-8 ./Messages_hi.properties.orig ../Messages_hi.properties
/usr/bin/native2ascii -encoding UTF-8 ./JSMessages_en.properties.orig ../JSMessages_en.properties
/usr/bin/native2ascii -encoding UTF-8 ./JSMessages_fr.properties.orig ../JSMessages_fr.properties
/usr/bin/native2ascii -encoding UTF-8 ./BackendMessages_en.properties.orig ../BackendMessages_en.properties
/usr/bin/native2ascii -encoding UTF-8 ./BackendMessages_fr.properties.orig ../BackendMessages_fr.properties
/usr/bin/native2ascii -encoding UTF-8 ./HelpMessages_en.properties.orig ../HelpMessages_en.properties
/usr/bin/native2ascii -encoding UTF-8 ./HelpMessages_fr.properties.orig ../HelpMessages_fr.properties